"""
V1 Registry — Single source of truth.
8 systems with strict miner telemetry.
"""

V1 = {
    'PRL': {
        'network_id': 'pearl-mainnet',
        'asset_id': 'PRL',
        'name': 'Pearl',
        'category': 'useful-work',
        'physical_resource': 'H100/H200 GPU',
        'resource_type': 'gpu_compute',
        'work_unit': 'noisy_gemm_work',
        'supplier_type': 'miner',
        'telemetry': 'pearld RPC + PearlTrack enrichment',
        'marginal_cost': 'Power + hardware amortization',
        'reward': 'Mining revenue (PRL/day)',
        'supply_response': 'GPU entry/exit based on profitability',
        'price_source': 'SafeTrade L2',
        'github': 'pearl-research-labs/pearl',
        'rpc': 'pearld JSON-RPC',
        'explorer': 'prlscan.com',
        'pools': ['Kryptex', 'PearlPool', 'Hero Miners'],
        'hardware': ['H100', 'H200', 'RTX_4090', 'CMP 170HX'],
        'recoverability': {
            'blocks': 'reconstructable',
            'pool_flows': 'reconstructable',
            'miner_wallets': 'reconstructable',
            'L2': 'irreversible',
        },
        'priority': 'P0',
        'cadence_seconds': 60,
    },
    'QUBIC': {
        'network_id': 'qubic-mainnet',
        'asset_id': 'QUBIC',
        'name': 'Qubic',
        'category': 'useful-work',
        'physical_resource': 'CPU compute',
        'resource_type': 'cpu_compute',
        'work_unit': 'useful_pow',
        'supplier_type': 'computor',
        'telemetry': 'Qubic RPC + static registry',
        'marginal_cost': 'Power + hardware amortization',
        'reward': 'Epoch rewards (QUBIC)',
        'supply_response': 'Computor changes per epoch',
        'price_source': 'SafeTrade L2',
        'github': 'qubic/core',
        'rpc': 'rpc.qubic.org',
        'explorer': 'explorer.qubic.org',
        'recoverability': {
            'ticks': 'reconstructable',
            'epochs': 'reconstructable',
            'computors': 'reconstructable',
            'L2': 'irreversible',
        },
        'priority': 'P0',
        'cadence_seconds': 60,
    },
    'QUAN': {
        'network_id': 'quantus-mainnet',
        'asset_id': 'QUAN',
        'name': 'Quantus',
        'category': 'useful-work',
        'physical_resource': 'GPU/CPU',
        'resource_type': 'gpu_compute',
        'work_unit': 'poseidon2_pow',
        'supplier_type': 'miner',
        'telemetry': 'Prometheus metrics + node RPC',
        'marginal_cost': 'Power + hardware amortization',
        'reward': 'Block reward (QUAN)',
        'supply_response': 'Miner entry based on profitability',
        'price_source': 'SafeTrade L2',
        'github': 'Quantus-Network/chain',
        'prometheus': ':9900',
        'recoverability': {
            'blocks': 'reconstructable',
            'difficulty': 'reconstructable',
            'L2': 'irreversible',
        },
        'priority': 'P0',
        'cadence_seconds': 60,
    },
    'XMR': {
        'network_id': 'monero-mainnet',
        'asset_id': 'XMR',
        'name': 'Monero',
        'category': 'pow-privacy',
        'physical_resource': 'CPU',
        'resource_type': 'cpu_mining',
        'work_unit': 'randomx_hash',
        'supplier_type': 'miner',
        'telemetry': 'monerod RPC + pool APIs',
        'marginal_cost': 'Power + CPU depreciation',
        'reward': 'Block reward (0.6 XMR tail)',
        'supply_response': 'CPU entry/exit',
        'price_source': 'CEX (Kraken, etc)',
        'github': 'monero-project/monero',
        'rpc': 'monerod RPC',
        'recoverability': {
            'blocks': 'reconstructable',
            'difficulty': 'reconstructable',
            'emission': 'reconstructable',
        },
        'priority': 'P0',
        'cadence_seconds': 120,
    },
    'KAS': {
        'network_id': 'kaspa-mainnet',
        'asset_id': 'KAS',
        'name': 'Kaspa',
        'category': 'control',
        'physical_resource': 'ASIC',
        'resource_type': 'asic_mining',
        'work_unit': 'kheavyhash',
        'supplier_type': 'miner',
        'telemetry': 'Node RPC + pool APIs',
        'marginal_cost': 'Power + ASIC depreciation',
        'reward': 'Block reward (KAS)',
        'supply_response': 'ASIC entry/exit',
        'price_source': 'CEX',
        'github': 'kaspanet/rusty-kaspa',
        'block_rate': 10,
        'recoverability': {
            'blocks': 'reconstructable',
            'daa': 'reconstructable',
            'difficulty': 'reconstructable',
        },
        'priority': 'P1',
        'cadence_seconds': 60,
    },
    'CLORE': {
        'network_id': 'clore-marketplace',
        'asset_id': 'CLORE',
        'name': 'Clore',
        'category': 'resource-market',
        'physical_resource': 'GPU marketplace',
        'resource_type': 'gpu_rental',
        'work_unit': 'gpu_hour',
        'supplier_type': 'provider',
        'telemetry': 'Clore API + GigaSPOT',
        'marginal_cost': 'Rental opportunity cost',
        'reward': 'Rental revenue (CLORE/USD)',
        'supply_response': 'Provider supply changes',
        'price_source': 'CEX',
        'api': 'clore.ai/api-docs',
        'gigaspot': 'GigaSPOT API',
        'recoverability': {
            'marketplace': 'irreversible',
            'bids_asks': 'irreversible',
        },
        'priority': 'P0',
        'cadence_seconds': 300,
    },
    'AKT': {
        'network_id': 'akash-mainnet',
        'asset_id': 'AKT',
        'name': 'Akash',
        'category': 'resource-market',
        'physical_resource': 'GPU/CPU capacity',
        'resource_type': 'compute_capacity',
        'work_unit': 'compute_hour',
        'supplier_type': 'provider',
        'telemetry': 'Akash provider API',
        'marginal_cost': 'Rental opportunity cost',
        'reward': 'Lease revenue (AKT)',
        'supply_response': 'Provider capacity changes',
        'price_source': 'CEX',
        'api': 'akash.network/docs/api-documentation',
        'recoverability': {
            'providers': 'irreversible',
            'gpu_capacity': 'irreversible',
            'leases': 'irreversible',
        },
        'priority': 'P0',
        'cadence_seconds': 300,
    },
    'NOS': {
        'network_id': 'nosana-mainnet',
        'asset_id': 'NOS',
        'name': 'Nosana',
        'category': 'resource-market',
        'physical_resource': 'GPU compute',
        'resource_type': 'gpu_compute',
        'work_unit': 'gpu_hour',
        'supplier_type': 'host',
        'telemetry': 'Nosana API',
        'marginal_cost': 'Rental cost',
        'reward': 'Job revenue (NOS)',
        'supply_response': 'Host supply changes',
        'price_source': 'CEX',
        'api': 'learn.nosana.com/api',
        'recoverability': {
            'markets': 'irreversible',
            'hosts': 'irreversible',
            'jobs': 'irreversible',
        },
        'priority': 'P0',
        'cadence_seconds': 300,
    },
}

def get_v1():
    return V1

def get_v1_coin(symbol):
    return V1.get(symbol.upper())

def get_v1_symbols():
    return list(V1.keys())
